name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Running cmake
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..

    - name: Build project
      run: |
        cd ${{ github.workspace }}
        cd build
        make

